### PR TITLE
Add fill_char option to StatusBar

### PR DESCRIPTION
**Pull request by dansondergaard**
A new release soon would be nice since gwf depends on this.

### CODE REVIEW

**Comment by mailund** [comment]
I've made version 0.1.3 now.

**Comment by dansondergaard** [comment]
Ok, I'm a retard. I should have forwarded the `fill_char` option from StatusTable to StatusBar... Can you fix it so I don't have to make a new PR?

**Comment by mailund** [comment]
I'm on it!

**Comment by mailund** [comment]
Should be done now.

**Comment by dansondergaard** [comment]
Great, I'd appreciate a 0.1.4 then ;) Thanks!

**Comment by mailund** [comment]
NP.

**Pull request closed without merging**
